"""
Django settings for django_novel project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-((qt%&!#&1r&n=1ty%t34chj91-mtz*btk0osif3uckkcav=gh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userapp',
    'mainapp',
    'operateapp',
    'DjangoUeditor',
    'captcha',  # 验证码
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_novel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_novel.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# 使用自己的数据库
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_novel',
        'USER': 'root',
        'PASSWORD': '010466',
        'HOST': 'localhost',
        'PORT': '3306',

    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 配置使用自己的授权类 Auth
AUTH_USER_MODEL = 'userapp.CustomUser'

# 上传文件绝对路径
MEDIA_ROOT = BASE_DIR / 'media'
# 配置访问路由
MEDIA_URL = '/media/'

# 支持上传单张的图片
X_FRAME_OPTIONS = 'sameorigin'

# 在外部使用static
STATICFILES_DIRS = [BASE_DIR / 'static']

# 验证码的样式设置
CAPTCHA_FONT_SIZE = 22

CAPTCHA_CHALLENGE_FUNCT = "captcha.helpers.math_challenge"

CAPTCHA_NOISE_FUNCTIONS = ("captcha.helpers.noise_dots",)

# 发送邮件
# 服务器的名称
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 服务器地址
EMAIL_HOST = 'smtp.163.com'
# 非SSL协议端口号
EMAIL_PORT = 25

EMAIL_USE_TLS = False
EMAIL_USE_SSL = False

# 使用当地的时间
EMAIL_USE_LOCALTIME = True
# 默认发送邮件的用户
DEFAULT_FROM_EMAIL = 'yxh17538146236@163.com'
# 邮件的用户
EMAIL_HOST_USER = 'yxh17538146236@163.com'
# 用户的密码，由于不能直接显示  改为授权码
EMAIL_HOST_PASSWORD = 'GUGWKETSFFGZQBEJ'
