# Generated by Django 3.2.4 on 2021-07-13 06:11

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='标签名')),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='小说名')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('author', models.CharField(max_length=10, verbose_name='作者名')),
                ('status', models.CharField(choices=[('0', '已完结'), ('1', '连载中')], default='0', max_length=1)),
                ('img', models.ImageField(upload_to='novels/imgs/', verbose_name='封面')),
                ('info', DjangoUeditor.models.UEditorField(verbose_name='小说介绍')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='mainapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='章节名')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='文章正文')),
                ('num', models.CharField(default='1', max_length=10, verbose_name='章节数')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel', to='mainapp.novel')),
            ],
        ),
    ]
