# Generated by Django 3.2.4 on 2021-07-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
