# Generated by Django 3.2.4 on 2021-07-22 07:50

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_novel_counter'),
        ('operateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='评论的内容')),
                ('state', models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '未通过')], default=0, verbose_name='审核状态')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mainapp.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='回复正文')),
                ('state', models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '未通过')], default=0, verbose_name='审核状态')),
                ('talking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='operateapp.talking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
